# Generated by Django 3.1.7 on 2021-03-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0002_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pitch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingsbackend.pitch'),
            preserve_default=False,
        ),
    ]
