# Generated by Django 3.1.7 on 2021-03-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0004_guest_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bookingsbackend.guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='booking',
            field=models.ManyToManyField(to='bookingsbackend.Booking'),
        ),
    ]
