# Generated by Django 3.1.7 on 2021-03-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0005_auto_20210326_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehiclereg',
            field=models.ManyToManyField(to='bookingsbackend.Vehicle'),
        ),
    ]
