# Generated by Django 3.1.7 on 2021-04-13 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0006_auto_20210327_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('adult', models.FloatField()),
                ('child', models.FloatField()),
                ('infant', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingsbypitch', to='bookingsbackend.pitch'),
        ),
    ]
