# Generated by Django 3.1.7 on 2021-04-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0007_auto_20210413_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('method', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookingsbackend.booking')),
            ],
        ),
    ]
