# Generated by Django 3.1.7 on 2021-04-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0008_auto_20210417_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookingsbypitch', to='bookingsbackend.pitch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentsbybooking', to='bookingsbackend.booking'),
        ),
    ]
