# Generated by Django 3.1.7 on 2021-04-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0009_auto_20210417_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkedin',
            field=models.BooleanField(default=False),
        ),
    ]
