# Generated by Django 3.1.7 on 2021-04-24 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0010_booking_checkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='eta',
            field=models.TimeField(default=datetime.time(10, 33, 45)),
            preserve_default=False,
        ),
    ]
