# Generated by Django 3.1.7 on 2021-04-25 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0011_booking_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2021, 4, 25)),
            preserve_default=False,
        ),
    ]
