# Generated by Django 3.1.7 on 2021-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0013_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('BACS', 'BACS'), ('Card', 'Card')], max_length=20),
        ),
    ]
