# Generated by Django 3.1.7 on 2021-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0014_auto_20210501_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='creationdate',
        ),
        migrations.AddField(
            model_name='payment',
            name='lasteditdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('BACS', 'BACS')], max_length=20),
        ),
    ]
