# Generated by Django 3.1.7 on 2021-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0015_auto_20210501_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='eta',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Card', 'Card'), ('BACS', 'BACS'), ('Cash', 'Cash')], max_length=20),
        ),
    ]
