# Generated by Django 3.1.7 on 2021-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0017_auto_20210501_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BACS', 'BACS'), ('Cash', 'Cash'), ('Card', 'Card')], max_length=20),
        ),
    ]
