# Generated by Django 3.1.7 on 2021-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0018_auto_20210501_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalpayments',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('BACS', 'BACS'), ('Card', 'Card')], max_length=20),
        ),
    ]
