# Generated by Django 3.1.7 on 2021-05-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsbackend', '0020_auto_20210501_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BACS', 'BACS'), ('Cash', 'Cash'), ('Card', 'Card')], max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.BooleanField()),
                ('comment', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsbybooking', to='bookingsbackend.booking')),
            ],
        ),
    ]
